name: py-terminal
version: '1.0.0'
summary: A powerful terminal-based UI web project using Python and Rich
description: |
  A terminal-based UI application with beautiful formatting, interactive menus,
  and advanced command execution capabilities. Features dual execution modes
  (interactive and capture) for different use cases.

grade: stable
confinement: strict

base: core20

apps:
  py-terminal:
    command: bin/py-terminal
    plugs:
      - home
      - network
      - process-control
    environment:
      PYTHONPATH: $SNAP/lib/python3.8/site-packages:$SNAP/usr/lib/python3/dist-packages

parts:
  py-terminal:
    plugin: python
    source: .
    python-packages:
      - rich>=10.0.0
    build-packages:
      - python3-dev
      - python3-pip
      - python3-setuptools
    stage-packages:
      - python3
      - python3-pip
    organize:
      terminal_web: lib/python3.8/site-packages/terminal_web
      info.md: lib/python3.8/site-packages/info.md
    build-environment:
      - PYTHONPATH: $SNAPCRAFT_STAGE/lib/python3.8/site-packages 